import LoadableComponent from './../Loadable/index';
import { HomeOutlined, UserOutlined, TagsOutlined, AppstoreOutlined, InfoCircleOutlined } from '@ant-design/icons';

export const userRouter: any = [
  {
    path: '/user',
    name: 'User',
    title: 'User',
    component: LoadableComponent(() => import('../../components/Layout/UserLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/user/login',
    name: 'LogIn',
    title: 'LogIn',
    component: LoadableComponent(() => import('../../scenes/Login')),
    showInMenu: false,
  },
];

export const appRouters: any = [
  {
    path: '/',
    exact: true,
    name: 'Home',
    permission: '',
    title: 'Home',
    component: LoadableComponent(() => import('../../components/Layout/AppLayout')),
    isLayout: true,
    showInMenu: false,
  },
  {
    path: '/dashboard',
    name: 'Dashboard',
    permission: 'dashboard.view',
    title: 'Dashboard',
    icon: HomeOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Dashboard')),
  },
  {
    path: '/ksube/:id',
    permission: 'ksube.view',
    title: 'KSube',
    name: 'KSube',
    icon: UserOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/KSube')),
  },
  {
    path: '/ksubedetay/:id',
    permission: 'ksube.detail',
    title: 'KSubeDetay',
    name: 'KSubeDetay',
    icon: UserOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/KSubeDetay')),
  },
  {
    path: '/bolgemudurluk',
    permission: 'kbolge.view',
    title: 'KBolge',
    name: 'KBolge',
    icon: UserOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/KBolge')),
  },
  {
    path: '/users',
    permission: 'user.view',
    title: 'Users',
    name: 'Users',
    icon: UserOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Users')),
  },
  {
    path: '/roles',
    permission: 'role.view',
    title: 'Roles',
    name: 'Roles',
    icon: TagsOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Roles')),
  },
  {
    path: '/tenants',
    permission: 'tenants',
    title: 'Tenants',
    name: 'Tenants',
    icon: AppstoreOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Tenants')),
  },
  {
    path: '/home',
    permission: 'home.view',
    title: 'Home',
    name: 'Home',
    icon: InfoCircleOutlined,
    showInMenu: true,
    component: LoadableComponent(() => import('../../scenes/Home')),
  },
  {
    path: '/logout',
    permission: '',
    title: 'Logout',
    name: 'Logout',
    showInMenu: false,
    component: LoadableComponent(() => import('../../components/Logout')),
  },
  {
    path: '/exception?:type',
    permission: '',
    title: 'Exception',
    name: 'Exception',
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/Exception')),
  },
  {
    path:        '/knormrequestdetail/:id',
    permission: 'kNormRequestDetail',
    title:      'KNormRequestDetail',
    name:       'KNormRequestDetail',
    icon: UserOutlined,
    showInMenu: false,
    component: LoadableComponent(() => import('../../scenes/KNormRequestDetail')),
  },
];

export const routers = [...userRouter, ...appRouters];
